### PR TITLE
implemented issue #104 (buffering of form values)

### PR DESCRIPTION
**Pull request by xylo**
OK, here is the buffering of form values discussed in #104.

Please tell me if something should be changed/improved.

### CODE REVIEW

**Comment by amischler** [comment]
Thanks for this PR ! The implementation and unit tests looks fine.
I'm just wondering about what should happen in case the bean is modified during the form edition. In your implementation, if a property is updated outside of the bean, the form doesn't get updated. It's required to call reload() to get the updated property value in the form. Don't you think the form should get automatically updated in this case ?

**Comment by xylo** [comment]
Interesting idea.  I can image many cases in which one would like the form values to be updated automatically when the bean property changes.  But I also know some cases where it's not wanted.

I would suggest to implement the automatic update as the default and add on option to the FXFormBuilder to deactivate it if necessary.  I can add it to my PR...

**Comment by amischler** [comment]
You are right, it should be configurable.

Actually, the buffering is directional. There is one buffering from user input to bean and one buffering from bean to form. 

So maybe the buffered option should take arguments to enable these two buffering directions independently ? Something like buffered(boolean userInput, boolean bean) ? Or maybe you have a better idea ?

**Comment by xylo** [comment]
I agree.  Two positive flags (bufferUserInput, bufferBeanChange) are better than one positive and one negative flag.  Moreover, it's even more flexible now.

**Comment by xylo** [comment]
Oh. I accidentally closed this.

**Comment by amischler** [comment]
Very nice, I merge the PR.

**Comment by amischler** [comment]
Deployed in 8.0.19-SNAPSHOT

**Comment by xylo** [comment]
Thanks!

**Pull request merged**
